test_that("p stars are reported correctly", {
  expect_equal(pstars(NA), "")
  expect_equal(pstars(NULL), "")
  expect_equal(pstars("a"), "")
  expect_equal(pstars("0.03"), "*")
  expect_equal(pstars("0.003"), "**")
  expect_equal(pstars("0.0003"), "***")
  expect_equal(pstars(NA, ls = TRUE), "")
  expect_equal(pstars(NULL, ls = TRUE), "")
  expect_equal(pstars("a", ls = TRUE), "")
  expect_equal(pstars("0.03", ls = TRUE), " *")
  expect_equal(pstars("0.003", ls = TRUE), " **")
  expect_equal(pstars("0.0003", ls = TRUE), " ***")
  expect_equal(pstars(NA, ts = TRUE), "")
  expect_equal(pstars(NULL, ts = TRUE), "")
  expect_equal(pstars("a", ts = TRUE), "")
  expect_equal(pstars("0.03", ts = TRUE), "* ")
  expect_equal(pstars("0.003", ts = TRUE), "** ")
  expect_equal(pstars("0.0003", ts = TRUE), "*** ")
  expect_equal(pstars(NA, ls = TRUE, ts = TRUE), "")
  expect_equal(pstars(NULL, ls = TRUE, ts = TRUE), "")
  expect_equal(pstars("a", ls = TRUE, ts = TRUE), "")
  expect_equal(pstars("0.03", ls = TRUE, ts = TRUE), " * ")
  expect_equal(pstars("0.003", ls = TRUE, ts = TRUE), " ** ")
  expect_equal(pstars("0.0003", ls = TRUE, ts = TRUE), " *** ")
})
